# 
# CircleCI 2.0 Gatsby to Firebase Configuration File
#

version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-
      
      - run:
          name: Install Global Dependencies
          command: npm install
          
      - run:
          name: Install Functions Dependencies
          command: cd ./functions && npm install

      - save_cache: 
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
            
          paths:
            - ./node_modules          

      - run:
         name: Gatsby Build
         command: ./node_modules/.bin/gatsby build

      - run:
          name: Firebase Select Project
          command: ./node_modules/.bin/firebase use --add autotagger-11064  --token=1/eTP0-HF7AeDu1BdurG8Sw-fMq7bPoeXomPgusEeWnf8

      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token=1/eTP0-HF7AeDu1BdurG8Sw-fMq7bPoeXomPgusEeWnf8

      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase serve --token=1/eTP0-HF7AeDu1BdurG8Sw-fMq7bPoeXomPgusEeWnf8