# 
# CircleCI 2.0 Gatsby to Firebase Configuration File
#

version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-
      
      - run:
          name: Install Global Dependencies
          command: npm install
          
      - run:
          name: Install Functions Dependencies
          command: cd ./functions && npm install

      - save_cache: 
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
            
          paths:
            - ./node_modules          

      - run:
         name: Gatsby Build
         command: ./node_modules/.bin/gatsby build

      - run:
          name: Firebase Select Project
          command: ./node_modules/.bin/firebase use --add autotagger-11064  --token=1/eTP0-HF7AeDu1BdurG8Sw-fMq7bPoeXomPgusEeWnf8
      
      - run:
          name: Firebase set config
          command: cd ./functions && firebase functions:config:set shopify.app_api_key="35911909788e811a55d8df65e1114e10" shopify.app_shared_secret="53494077ff5dd7d317a83d828c254264" shopify.app_url="https://autotagger-11064.firebaseapp.com" shopify.app_name_url="kea-autotagger" shopify.app_scopes="read_products" fire.project_id="autotagger-11064" fire.client_email="firebase-adminsdk-lpycn@autotagger-11064.iam.gserviceaccount.com" fire.private_key="-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCr5OJW3HNQWZdr\nTnNA0+oSZcTy4VruaclVZFJjtSMaa10gbrjrUL6ssvLQtFciEqdwp9uNoVoW7Z3F\ngZjktxxHdUnmE6I5Qhz0coCoHR9eEfZwVp4QDwOrCucfEqCuU3it8DXWlpE8e8JL\nHWdHwx8oOV7pCJKFD15PQJd0FTdyQjzehEOFAzvRDlsfIihoijUwlzwKNEAYvpvb\nPBUXCORffd0+O/Tsi6rwToC8p7hsERKfr7wMZUAG+9JflyUea0gdFCpas6/hEXeq\nKydMh+Hx94vMqVrjdbC47N9Y7I1rHGkK79YhnloV2Eun+0upEkdniMWyqlRGHnDN\nqj8PTFIpAgMBAAECggEAG7c5A3ZiJXd8obGxhadlm3fLTLonVj+6VclqO2dudIkR\nJ/SSXmbTh7cGzb32Oqk1VEXMccatZvsDMGBYDbC0n5T6yF0sD/1n+8YmlnSzpRBS\nYwSkUcSJ+98zKuBvBgyxbaJInAQFAPKXflMMXxbIBE1Tz1ExhsDWnQK2KOJu4T4m\nzk0xiIv4h5hptlspinzn4XiELbul1PMNjaH7s+fA6k2vxaqT5PtNhenW+UJV9MsN\nS/JBc0CHlAEQRtKnBhw/y+SOBNHgI+qoc2VB7Y/DKEjs4FwFt2BXILM5GD6yomlq\n9RmCPbmfxTS2x3C9/kfNLRJPp01xmcOIp4B/s4+aHQKBgQDqlKnn3goYTmk8If9n\neAXUIGvnIFSV9EZXLx4CNFKBJ/XONdW+6/I7tslX0L5gvOJI53pp22eh9vw8sr/p\nHwTQmf5sRJuAC1JSHt34k0+y+5b3Y7i5ZudFHovpnufZ53zs7/0p2awYUH5tEzZ1\nUfY3qEhWzC54SjYyZe8sSj01ywKBgQC7lurDZVTuOQv0WyMYZ7lm2BmO22P5r/fO\n0ZUplqFvpMcePQjgnXXVbjQmTXzgOJH+JTzevY10Fulcvva7e4eP8/imF9dh3g+q\ni6wFWWlk3WwPIj/4Zq21ZUQcejxBVSfSYxUv8hdiSWvk7LjiFuorGgpRc08wMJim\naHpiTbA5WwKBgQCKGyxMznSzCrb6KCnuCMOlt9DPKkGiZ0ZiXeMU+Sj50UTuOtO0\nq8TZUywG/2aWHZ47vcxcNkg1Guw18Cb8YL688WzQ4TOLlx7IKlQU3OW3QlgHHjbL\nMMJH90v4Jw3pRFhQRpqN4RFo3zsPjJgrSi3jZrfwIhXZzBdMZKcDNFIFMQKBgB2r\ny0pIttxPTaLC35Q2o86uk6xS60dNHAcsg0lmt/YuvAf+Y28TuNWfbsQ4MW5NxFnM\njgo1NTCNhy/STLhu24xbbJLo5npmY1f4a6cU82Su2S6zniauJv+wGsveUbWLwJa4\ncVt6EVTMhDJbdwrb0QIsRkGH2Zintx1rHSB7ZUpNAoGAYgOG5BchPsOp8UXLzS2u\nTgNhFhsZraGUM/sJH4/hx7X8eSrRUpARTFCZ3PtBM67Ubcg1nYh+Acjortha97qu\nH/CLOfe49vQEjgtr6EWtMEcyQDk56cQUTwAUo8vf3idZw9jUGnJ09OQFiNK9pFLV\n+zdVImZrA1B+1RLlX+EUnAk=\n-----END PRIVATE KEY-----\n" --token=1/eTP0-HF7AeDu1BdurG8Sw-fMq7bPoeXomPgusEeWnf8     

      - run:
          name: Firebase get config
          command: cd ./functions && firebase functions:config:get | ac .runtimeconfig.json --token=1/eTP0-HF7AeDu1BdurG8Sw-fMq7bPoeXomPgusEeWnf8

      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token=1/eTP0-HF7AeDu1BdurG8Sw-fMq7bPoeXomPgusEeWnf8

      - run:
          name: Firebase Serve
          command: ./node_modules/.bin/firebase serve --token=1/eTP0-HF7AeDu1BdurG8Sw-fMq7bPoeXomPgusEeWnf8